package com.zlyandroid.wanandroid.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zlyandroid.wanandroid.db.greendao.ReadLaterModel;
import com.zlyandroid.wanandroid.db.greendao.ReadRecordModel;
import com.zlyandroid.wanandroid.db.greendao.TodoData;

import com.zlyandroid.wanandroid.db.greendao.ReadLaterModelDao;
import com.zlyandroid.wanandroid.db.greendao.ReadRecordModelDao;
import com.zlyandroid.wanandroid.db.greendao.TodoDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readLaterModelDaoConfig;
    private final DaoConfig readRecordModelDaoConfig;
    private final DaoConfig todoDataDaoConfig;

    private final ReadLaterModelDao readLaterModelDao;
    private final ReadRecordModelDao readRecordModelDao;
    private final TodoDataDao todoDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readLaterModelDaoConfig = daoConfigMap.get(ReadLaterModelDao.class).clone();
        readLaterModelDaoConfig.initIdentityScope(type);

        readRecordModelDaoConfig = daoConfigMap.get(ReadRecordModelDao.class).clone();
        readRecordModelDaoConfig.initIdentityScope(type);

        todoDataDaoConfig = daoConfigMap.get(TodoDataDao.class).clone();
        todoDataDaoConfig.initIdentityScope(type);

        readLaterModelDao = new ReadLaterModelDao(readLaterModelDaoConfig, this);
        readRecordModelDao = new ReadRecordModelDao(readRecordModelDaoConfig, this);
        todoDataDao = new TodoDataDao(todoDataDaoConfig, this);

        registerDao(ReadLaterModel.class, readLaterModelDao);
        registerDao(ReadRecordModel.class, readRecordModelDao);
        registerDao(TodoData.class, todoDataDao);
    }
    
    public void clear() {
        readLaterModelDaoConfig.clearIdentityScope();
        readRecordModelDaoConfig.clearIdentityScope();
        todoDataDaoConfig.clearIdentityScope();
    }

    public ReadLaterModelDao getReadLaterModelDao() {
        return readLaterModelDao;
    }

    public ReadRecordModelDao getReadRecordModelDao() {
        return readRecordModelDao;
    }

    public TodoDataDao getTodoDataDao() {
        return todoDataDao;
    }

}
