package com.zlyandroid.wanandroid.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zlyandroid.wanandroid.db.greendao.TodoData;
import com.zlyandroid.wanandroid.db.greendao.ReadLaterModel;
import com.zlyandroid.wanandroid.db.greendao.ReadRecordModel;

import com.zlyandroid.wanandroid.db.greendao.TodoDataDao;
import com.zlyandroid.wanandroid.db.greendao.ReadLaterModelDao;
import com.zlyandroid.wanandroid.db.greendao.ReadRecordModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoDataDaoConfig;
    private final DaoConfig readLaterModelDaoConfig;
    private final DaoConfig readRecordModelDaoConfig;

    private final TodoDataDao todoDataDao;
    private final ReadLaterModelDao readLaterModelDao;
    private final ReadRecordModelDao readRecordModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoDataDaoConfig = daoConfigMap.get(TodoDataDao.class).clone();
        todoDataDaoConfig.initIdentityScope(type);

        readLaterModelDaoConfig = daoConfigMap.get(ReadLaterModelDao.class).clone();
        readLaterModelDaoConfig.initIdentityScope(type);

        readRecordModelDaoConfig = daoConfigMap.get(ReadRecordModelDao.class).clone();
        readRecordModelDaoConfig.initIdentityScope(type);

        todoDataDao = new TodoDataDao(todoDataDaoConfig, this);
        readLaterModelDao = new ReadLaterModelDao(readLaterModelDaoConfig, this);
        readRecordModelDao = new ReadRecordModelDao(readRecordModelDaoConfig, this);

        registerDao(TodoData.class, todoDataDao);
        registerDao(ReadLaterModel.class, readLaterModelDao);
        registerDao(ReadRecordModel.class, readRecordModelDao);
    }
    
    public void clear() {
        todoDataDaoConfig.clearIdentityScope();
        readLaterModelDaoConfig.clearIdentityScope();
        readRecordModelDaoConfig.clearIdentityScope();
    }

    public TodoDataDao getTodoDataDao() {
        return todoDataDao;
    }

    public ReadLaterModelDao getReadLaterModelDao() {
        return readLaterModelDao;
    }

    public ReadRecordModelDao getReadRecordModelDao() {
        return readRecordModelDao;
    }

}
