package com.zlyandroid.wanandroid.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODO_DATA".
*/
public class TodoDataDao extends AbstractDao<TodoData, Long> {

    public static final String TABLENAME = "TODO_DATA";

    /**
     * Properties of entity TodoData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Priority = new Property(2, int.class, "priority", false, "PRIORITY");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Date = new Property(5, long.class, "date", false, "DATE");
        public final static Property DateStr = new Property(6, String.class, "dateStr", false, "DATE_STR");
        public final static Property IsAccomplish = new Property(7, int.class, "isAccomplish", false, "IS_ACCOMPLISH");
        public final static Property User = new Property(8, String.class, "user", false, "USER");
    }


    public TodoDataDao(DaoConfig config) {
        super(config);
    }
    
    public TodoDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODO_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"PRIORITY\" INTEGER NOT NULL ," + // 2: priority
                "\"TYPE\" INTEGER NOT NULL ," + // 3: type
                "\"CONTENT\" TEXT," + // 4: content
                "\"DATE\" INTEGER NOT NULL ," + // 5: date
                "\"DATE_STR\" TEXT," + // 6: dateStr
                "\"IS_ACCOMPLISH\" INTEGER NOT NULL ," + // 7: isAccomplish
                "\"USER\" TEXT);"); // 8: user
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODO_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TodoData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getPriority());
        stmt.bindLong(4, entity.getType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
        stmt.bindLong(6, entity.getDate());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(7, dateStr);
        }
        stmt.bindLong(8, entity.getIsAccomplish());
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(9, user);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TodoData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getPriority());
        stmt.bindLong(4, entity.getType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
        stmt.bindLong(6, entity.getDate());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(7, dateStr);
        }
        stmt.bindLong(8, entity.getIsAccomplish());
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(9, user);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TodoData readEntity(Cursor cursor, int offset) {
        TodoData entity = new TodoData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getInt(offset + 2), // priority
            cursor.getInt(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.getLong(offset + 5), // date
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dateStr
            cursor.getInt(offset + 7), // isAccomplish
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // user
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TodoData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPriority(cursor.getInt(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDate(cursor.getLong(offset + 5));
        entity.setDateStr(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsAccomplish(cursor.getInt(offset + 7));
        entity.setUser(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TodoData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TodoData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TodoData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
